import { Casa } from "./interface/casa";

export const Lugares:Casa[]=[
    {
        imagen: ['assets/imagenes/Casas/Zapopan/Zapopan.webp','assets/imagenes/Casas/Zapopan/Zapopan1.webp','assets/imagenes/Casas/Zapopan/Zapopan2.webp','assets/imagenes/Casas/Zapopan/Zapopan3.webp'],
        nombre: 'Alojamiento entero: departamento con servicios incluidos',
        direccion: '694 Emiliano Zapata',
        calificacion: 4.71,
        descripcion:'2 huéspedes - 1 habitación - 1 cama - 1 baño',
        lugar: ['Zapopan','Jalisco', 'México'],
        anfitrion: 'Oscar',
        precio: 315,
        ofrece: ['Cocina', 'Tv', 'Wifi'],
        id: 0
    },
    {
        imagen: ['assets/imagenes/Casas/Aguascalientes/Aguas1.webp', 'assets/imagenes/Casas/Aguascalientes/Aguas2.webp', 'assets/imagenes/Casas/Aguascalientes/Aguas3.webp', 'assets/imagenes/Casas/Aguascalientes/Aguas4.webp'],
        nombre: 'Alojamiento entero: suit con entrada independiente',
        direccion: '206 Sierra Morena, Bosques del Prado Norte',
        calificacion: 4.82,
        descripcion:'2 huéspedes - 1 estudio - 1 cama - 1 baño',
        lugar: ['Aguascalientes','México', 'México'],
        anfitrion: 'Luis Salvador',
        precio: 326,
        ofrece: ['Tv', 'Wifi', 'Refrigerador', 'Plancha'],
        id: 1
    },
    {
        imagen: ['assets/imagenes/Casas/Guadalajara/GuadalajaraCopy.png','assets/imagenes/Casas/Guadalajara/Guadalajara1.webp','assets/imagenes/Casas/Guadalajara/Guadalajara2.webp','assets/imagenes/Casas/Guadalajara/Guadalajara3.webp' ],
        nombre: 'Habitación privada en vivienda rentada',
        direccion: '441 Calle Marsella, Obrera',
        calificacion: 4.81,
        descripcion:'2 huéspedes - 1 habitación - 1 cama - 1 baño',
        lugar: ['Guadalajara', 'Jalisco', 'México'],
        anfitrion: 'Gysell Alejandra',
        precio: 489,
        ofrece: ['Wifi', 'Área para trabajar', 'Tv', 'Aire Acondicionadao', 'Ascensor'],
        id: 2
    },
    {
        imagen: ['assets/imagenes/Casas/Aguascalientes2/Aguas1.webp','assets/imagenes/Casas/Aguascalientes2/Aguas2.jpeg','assets/imagenes/Casas/Aguascalientes2/Aguas3.jpeg', 'assets/imagenes/Casas/Aguascalientes2/Aguas4.webp','assets/imagenes/Casas/Aguascalientes2/Aguas5.webp' ],
        nombre: 'Alojamiento entero',
        direccion: '2005 Av Independiente, Desarrollo Especial Galerías',
        calificacion: 4.90,
        descripcion:'6 huéspedes - 3 habitaciones - 4 camas - 2 baños completos y uno tocador',
        lugar: ['Aguascalientes', 'México', 'México'],
        anfitrion: 'Brenda',
        precio: 1496,
        ofrece: ['Cocina', 'Wifi', 'Tv', 'Plancha', 'Horno', 'Licuadora'],
        id: 3
    },
    {
        imagen: ['assets/imagenes/Casas/Mazatlan/Mazatlan1.webp','assets/imagenes/Casas/Mazatlan/Mazatlan2.webp', 'assets/imagenes/Casas/Mazatlan/Mazatlan3.jpeg', 'assets/imagenes/Casas/Mazatlan/Mazatlan4.jpeg' ],
        nombre: 'Alojamiento entero',
        direccion: '4724 Av. Ernesto Coppel Campaña',
        calificacion: 4.74,
        descripcion:'4 huéspedes - 2 habitaciones - 3 camas - 2 baños',
        lugar: ['Mazatlán', 'Sinaloa', 'México'],
        anfitrion: 'Joaquín',
        precio: 1760,
        ofrece: ['Vista a la playa', 'Wifi', 'Alberca uso compartido', 'Jacuzzi privado', 'Ascensor'],
        id: 4
    },
    {
        imagen: ['assets/imagenes/Casas/Guanajuato1/Guanajuato3.webp','assets/imagenes/Casas/Guanajuato1/Guanajuato1.webp', 'assets/imagenes/Casas/Guanajuato1/Guanajuato2.webp','assets/imagenes/Casas/Guanajuato1/Guanajuato4.webp', 'assets/imagenes/Casas/Guanajuato1/Guanajuato5.webp'],
        nombre: 'Tranquilidad y seguridad. Alojamiento entero',
        direccion: 'Carr a Puentecillas',
        calificacion: 5.0,
        descripcion:'5 huéspedes - 3 habitaciones - 4 camas - 2 baños completos y uno de tocador',
        lugar: ['Guanajuato', 'Guanajuato', 'México'],
        anfitrion: 'Héctor Rodolfo',
        precio: 1200,
        ofrece: ['Vista a la montaña', 'Vista al jardiín', 'Cocina', 'Wifi', 'Lavadora', 'Tv'],
        id: 5
    },
    {
        imagen: ['assets/imagenes/Casas/Tulum/RiveraMaya1.webp', 'assets/imagenes/Casas/Tulum/RiveraMaya2.webp', 'assets/imagenes/Casas/Tulum/RiveraMaya3.webp', 'assets/imagenes/Casas/Tulum/RiveraMaya4.webp', 'assets/imagenes/Casas/Tulum/RiveraMaya5.webp', 'assets/imagenes/Casas/Tulum/RiveraMaya6.webp'],
        nombre: 'Alojamiento entero',
        direccion: 'Nikte 101 Selva Norte Tulum',
        calificacion: 5.0,
        descripcion:'5 huéspedes - 2 habitaciones - 2 camas - 2 baños',
        lugar: ['Tulum', 'Quintana Roo', 'México'],
        anfitrion: 'Bellenty',
        precio: 809,
        ofrece: ['Wifi', 'Acceso al lago', 'Cocina', 'Tv', 'Ascensor'],
        id: 6
    },
    {
        imagen: ['assets/imagenes/Casas/Guanajuato/Guanajuato21.webp', 'assets/imagenes/Casas/Guanajuato/Guanajuato22.webp',  'assets/imagenes/Casas/Guanajuato/Guanajuato23.webp', 'assets/imagenes/Casas/Guanajuato/Guanajuato24.webp', 'assets/imagenes/Casas/Guanajuato/Guanajuato25.webp', 'assets/imagenes/Casas/Guanajuato/Guanajuato26.webp'],
        nombre: 'Alojamiento entero: condominio en Marfil',
        direccion: '70 Mineral de Valenciana',
        calificacion: 5.0,
        descripcion:'6 huéspedes - 3 habitaciones - 2 baños',
        lugar: ['Guanajuato', 'Guanajuato', 'México'],
        anfitrion: 'Julieta',
        precio: 1297,
        ofrece: ['Vista al hirizonte de la ciudad', 'Cocina', 'Wifi', 'Área de trabajo', 'Tv', 'Estacionamiento'],
        id: 7

    },
    {
        imagen: ['assets/imagenes/Casas/Colima/Colima1.webp', 'assets/imagenes/Casas/Colima/Colima2.webp', 'assets/imagenes/Casas/Colima/Colima3.webp', 'assets/imagenes/Casas/Colima/Colima4.jpeg'],
        nombre: 'Alojamiento entero',
        direccion: '195 de los Diamantes',
        calificacion: 4.84,
        descripcion:'6 huéspedes - 2 habitaciones - 3 camas - 1 baño',
        lugar: ['Colima', 'Colima', 'México'],
        anfitrion: 'Gaby',
        precio: 755,
        ofrece: ['Cocina', 'Wifi', 'Tv y Netflix', 'Refrigerador'],
        id: 8
    },
    {
        imagen: ['assets/imagenes/Casas/Durango/Durango1.jpeg', 'assets/imagenes/Casas/Durango/Durango2.jpeg','assets/imagenes/Casas/Durango/Durango3.webp','assets/imagenes/Casas/Durango/Durango4.webp','assets/imagenes/Casas/Durango/Durango5.jpeg'],
        nombre: 'Alojamiento entero',
        direccion: '411 Elorreaga',
        calificacion: 4.92,
        descripcion:'2 huéspedes - 1 habitación - 1 cama - 2 baños',
        lugar: ['Durango', 'Durango', 'México'],
        anfitrion: 'Victor',
        precio: 561,
        ofrece: [ 'Cafetera', 'Cocina', 'Wifi', 'Refrigerador', 'Tv con servicios de streaming', 'Área para trabajar'],
        id: 9
    },
    {
        imagen: ['assets/imagenes/Casas/Ciudad Victoria/CV1.webp', 'assets/imagenes/Casas/Ciudad Victoria/CV2.webp','assets/imagenes/Casas/Ciudad Victoria/CV3.webp','assets/imagenes/Casas/Ciudad Victoria/CV4.webp'],
        nombre: 'Alojamiento entero',
        direccion: '166 Ciudad Valle Hermoso',
        calificacion: 4.8,
        descripcion:'2 huéspedes - 1 habitación - 1 cama - 1 baño',
        lugar: ['Ciudad Victoria', 'Tamaulipas','México'],
        anfitrion: 'Dora Alicia',
        precio: 399,
        ofrece: [ 'Cafetera', 'Cocina', 'Wifi', 'Aire acondicionado', 'Tv', 'Secadora de pelo', 'Plancha'],
        id: 10
    },
    {
        imagen: ['assets/imagenes/Casas/Xochimilco/Xochimilco.webp', 'assets/imagenes/Casas/Xochimilco/Xochimilco1.webp' , 'assets/imagenes/Casas/Xochimilco/Xochimilco2.webp', 'assets/imagenes/Casas/Xochimilco/Xochimilco3.webp'],
        nombre: 'Habitación privada, Cabaña en el Lago Xochimilco',
        direccion: 'Pista Olímpica Virgilio Uribe',
        calificacion: 4.89,
        descripcion:'2 huéspedes - 1 habitación - 1 cama - 1 baño privado',
        lugar: ['Xochimilco', 'Ciudad de México', 'México'],
        anfitrion: 'Estefania',
        precio: 1100,
        ofrece: [ 'Acceso al lago', 'Mesa de ping pong', 'Wifi', 'Tv con servicios de streaming', 'Mini refrigerador', 'Microondas'],
        id: 11
    },
    {
        imagen: ['assets/imagenes/Casas/Nayarit/Nayarit.webp', 'assets/imagenes/Casas/Nayarit/Nayarit1.webp', 'assets/imagenes/Casas/Nayarit/Nayarit2.webp', 'assets/imagenes/Casas/Nayarit/Nayarit3.webp'],
        nombre: 'Alojamiento entero: suite con entrada independiente',
        direccion: 'Bahia de Banderas, Nayarit',
        calificacion: 4.92,
        descripcion:'3 huéspedes - 1 habitación - 2 camas',
        lugar: ['Punta Negraa', 'Nayarit','México'],
        anfitrion: 'Cristina Shanti',
        precio: 1946,
        ofrece: [ 'Vista a la playa', 'Lavadora', 'Wifi', 'Tv', 'Lavadora', 'Refrigerador'],
        id: 12
    },
    {
        imagen: ['assets/imagenes/Casas/Visalia/Visalia.webp', 'assets/imagenes/Casas/Visalia/Visalia1.webp', 'assets/imagenes/Casas/Visalia/Visalia2.webp', 'assets/imagenes/Casas/Visalia/Visalia3.webp', 'assets/imagenes/Casas/Visalia/Visalia.webp4', 'assets/imagenes/Casas/Visalia/Visalia.webp5'],
        nombre: 'Alojamiento entero. Cerca del Parque Nacional de las Secuoyas',
        direccion: '1323 S Clover St, Visilia, CA 93277',
        calificacion: 4.98,
        descripcion:'8 huéspedes - 3 habitaciones - 4 cama - 1 baño',
        lugar: ['Visalia', 'California', 'Estados Unidos'],
        anfitrion: 'Jeanette',
        precio: 2727,
        ofrece: [ 'Cocina', 'Wifi', 'Área para trabajar', 'Tv', 'Alberca', 'Refrigerador'],
        id: 13
    },
    {
        imagen: ['assets/imagenes/Casas/SF/SF.webp', 'assets/imagenes/Casas/SF/SF1.webp', 'assets/imagenes/Casas/SF/SF2.webp', 'assets/imagenes/Casas/SF/SF3.webp'],
        nombre: 'Habitación privada, baño y armario ',
        direccion: '1501 Howard St, CA 94103',
        calificacion: 5.0,
        descripcion:'2 huéspedes - 1 habitación - 1 cama - 1 baño',
        lugar: ['San Francisco', 'California', 'Estados Unidos'],
        anfitrion: 'Daniel',
        precio: 1715,
        ofrece: [ 'Acceso al lago', 'Mesa de ping pong', 'Wifi', 'Tv con servicios de streaming', 'Mini refrigerador', 'Microondas'],
        id: 14
    },
]